const express = require('express')
const router = express.Router()
const { getOnt, getOntById, createDataOnt, updateDataOnt, destroyOnt, getOntIdle, fetchListOnt } = require('./controllers/ontController.js')
const { getOlt, getOltById, createDataOlt, updateDataOlt, destroyOlt } = require('./controllers/oltController.js')
const { getPon, getPonById, createDataPon, updateDataPon, destroyPon, getPonForOptions, Test } = require('./controllers/ponController.js')
const { getOdp, getOdpById, createDataOdp, updateDataOdp, destroyOdp, getOdpForSelect } = require('./controllers/odpController.js')
const { getGpon, getGponById, createDataGpon, updateDataGpon, destroyGpon, getGponSelect } = require('./controllers/gponController.js')
const { getCostumer, getCostumerById, createDataCostumer, updateDataCostumer, destroyCostumer, showListCostumer } = require('./controllers/costumerController.js')
const loginAd = require('./controllers/ad.js')
const requireAuth = require('./middleware/requireAuth.js')
const { fetchDismantle, fetchDismantleById, createDismantle, updateDismantle, destroyDismantle } = require('./controllers/dismantleController.js')
const { fetchHistory } = require('./controllers/historyController.js')
const { fetchReport } = require('./controllers/reportController.js')
const { fetchInstallation, createInstallation, updateInstallation, destroyInstallation, fetchInstallationById } = require('./controllers/installationController.js')

router.post('/login', loginAd)
router.use(requireAuth)
router.get('/ont', getOnt)
router.get('/ont-list', fetchListOnt)
router.get('/ont-idle', getOntIdle)
router.get('/ont-ip', getOntById)
router.post('/ont', createDataOnt)
router.patch('/ont', updateDataOnt)
router.delete('/ont', destroyOnt)

router.get('/olt', getOlt)
router.get('/olt/:id', getOltById)
router.post('/olt', createDataOlt)
router.patch('/olt', updateDataOlt)
router.delete('/olt/:id', destroyOlt)

router.get('/pon', getPon)
router.get('/pon/:id', getPonById)
router.get('/pon-select', getPonForOptions)
router.post('/pon', createDataPon)
router.patch('/pon', updateDataPon)
router.delete('/pon/:id', destroyPon)

router.get('/odp', getOdp)
router.get('/odp/:id', getOdpById)
router.get('/odp-select', getOdpForSelect)
router.post('/odp', createDataOdp)
router.patch('/odp', updateDataOdp)
router.delete('/odp/:id', destroyOdp)

router.get('/gpon', getGpon)
router.get('/gpon-select', getGponSelect)
router.get('/gpon-id', getGponById)
router.post('/gpon', createDataGpon)
router.patch('/gpon', updateDataGpon)
router.delete('/gpon-delete', destroyGpon)

router.get('/costumer', getCostumer)
router.get('/costumer-list', showListCostumer)
router.get('/costumer/:id', getCostumerById)
router.post('/costumer', createDataCostumer)
router.patch('/costumer', updateDataCostumer)
router.delete('/costumer/:id', destroyCostumer)

router.get('/dismantle', fetchDismantle)
router.get('/dismantle/:id', fetchDismantleById)
router.post('/dismantle', createDismantle)
router.patch('/dismantle', updateDismantle)
router.delete('/dismantle/:id', destroyDismantle)

router.get('/installation', fetchInstallation)
router.get('/installation/:id', fetchInstallationById)
router.post('/installation', createInstallation)
router.patch('/installation', updateInstallation)
router.delete('/installation/:id', destroyInstallation)

router.get('/history', fetchHistory)

router.get('/report', fetchReport)

module.exports = router